---
image: fedora/39
oauth: pages.sr.ht/PAGES:RW
packages:
  - tar
  - hut
  - chromium # for puppeter
  - composer

sources:
  - https://github.com/nvm-sh/nvm.git

environment:
  SITE: tetov.se
  PUBLISH_REF: refs/heads/main

tasks:
  - nvm: |
      cd nvm
      git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`

  - build: |
      . nvm/nvm.sh
      cd tetov.se
      nvm install
      nvm use
      npm ci
      npm test
      npm run build
      tar -C public -cvz . > ../site.tar.gz

  - publish: >
      test "$GIT_REF" = "$PUBLISH_REF" &&
        hut pages publish
          -d "$SITE"
          --site-config tetov.se/srht_site_config.json
          site.tar.gz

triggers:
  - action: email
    condition: failure
    to: Anton Tetov <build.sr.ht@tetov.se>
