---
image: nixos/latest
oauth: pages.sr.ht/PAGES:RW

environment:
  site: tetov.se
  NIX_CONFIG: "experimental-features = nix-command flakes"

tasks:
  - install: |
      cd tetov.se
      nix develop --command npm ci
  - test: |
      cd tetov.se
      nix develop --command npm test
  - build: |
      cd tetov.se
      nix develop --command npm run build
      tar -C public -cvz . > ../site.tar.gz
  - publish: |
      cd tetov.se
      nix develop --command hut pages publish -d $site site.tar.gz --site-config tetov.se/srht_site_config.json

triggers:
  - action: email
    condition: failure
    to: Anton Tetov <build.sr.ht@tetov.se>
