---
image: nixos/latest
oauth: pages.sr.ht/PAGES:RW

environment:
  site: tetov.se
  NIX_CONFIG: "experimental-features = nix-command flakes"

tasks:
  - build: |
      nix develop tetov.se
      cd tetov.se
      npm ci
      npm test
      npm run build
      tar -C public -cvz . > ../site.tar.gz

  - publish: |
      nix develop tetov.se
      hut pages publish -d $site site.tar.gz --site-config tetov.se/srht_site_config.json

triggers:
  - action: email
    condition: failure
    to: Anton Tetov <build.sr.ht@tetov.se>
