---
image: nixos/latest
oauth: pages.sr.ht/PAGES:RW

environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
  SITE: tetov.se
  PUBLISH_REF: refs/heads/main

tasks:
  - install: |
      cd tetov.se
      nix develop --command npm ci

  - test: |
      cd tetov.se
      nix develop --command npm test

  - pre-commit-hooks: |
      cd tetov.se
      pre-commit run --all

  - build: |
      cd tetov.se
      nix develop --command npm run build
      tar -C public -cvz . > ../site.tar.gz

  - publish: |
      if [ "$GIT_REF" = "$PUBLISH_REF" ] ; then
        cd tetov.se
        nix develop --command hut pages publish -d "$SITE" ../site.tar.gz --site-config srht_site_config.json
      else
        echo 'Not publishing, because $GIT_REF != $PUBLISH_REF'
      fi

triggers:
  - action: email
    condition: failure
    to: Anton Tetov <build.sr.ht@tetov.se>
