---
root: true
settings:
  react:
    version: detect
env:
  es6: true
  jest: true
  node: true
extends: ["plugin:prettier/recommended"]
ignorePatterns: ["public/"]
overrides:
  - files: ["*.js"]
    extends:
      - "eslint:recommended"
      - "plugin:react/recommended"
    parserOptions:
      ecmaFeatures:
        ecmaVersion: 2022
        sourceType: module
  - files: ["*.ts", "*.tsx"]
    parser: "@typescript-eslint/parser"
    extends:
      - "eslint:recommended"
      - "plugin:react/recommended"
      - "plugin:@typescript-eslint/recommended"
      - "plugin:@typescript-eslint/recommended-requiring-type-checking"
    plugins:
      - "@typescript-eslint"
    parserOptions:
      project: ./tsconfig.json
    rules:
      react/prop-types: "off"
      "@typescript-eslint/explicit-function-return-type": "off"
  - files:
      - "*.graphql"
    parser: "@graphql-eslint/eslint-plugin"
    plugins:
      - "@graphql-eslint"
    rules:
      "@graphql-eslint/no-anonymous-operations": error
      "@graphql-eslint/naming-convention":
        - error
        - OperationDefinition:
            style: PascalCase
            forbiddenPrefixes:
              - Query
              - Mutation
              - Subscription
              - Get
            forbiddenSuffixes:
              - Query
              - Mutation
              - Subscription
