---
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.29.0"
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - "@babel/eslint-parser@7.19.1"
          - "@graphql-eslint/eslint-plugin@3.12.0"
          - "@typescript-eslint/eslint-plugin@5.41.0"
          - "@typescript-eslint/parser@5.41.0"
          - "eslint@8.26.0"
          - "eslint-config-prettier@8.5.0"
