---
exclude: "\\.spec$"
repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        language: system
        files: '\.[jt]sx?$'
        entry: npm run lint:fix
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/adrienverge/yamllint.git
    rev: "v1.29.0"
    hooks:
      - id: yamllint
