name: Deploy website to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Update npm
        run: npm install -g npm@latest

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Restore NPM cache
        uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Restore Gatsby cache
        uses: actions/cache@v3
        id: gatsby-cache
        with:
          path: |
            ./.cache
            ./public
          key: ${{ runner.os }}-gatsby-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gatsby-

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy on gh-pages
        if: github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@eb08c35b9fab86751edfff4e55cd5cde35ff0e52
        with:
          target_branch: gh-pages
          build_dir: public
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
