name: Deploy website to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: ./.git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1

      - name: Install Git LFS
        run: git lfs install

      - name: Git LFS Pull
        run: git lfs pull

      - name: Set up node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "14"

      - name: Install yarn
        run: npm install -g yarn

      - name: Restore Gatsby cache
        uses: actions/cache@v2
        id: gatsby-cache
        with:
          path: |
            ./.cache
            ./public
          key: ${{ runner.os }}-${{ github.ref }}-gatsby-cache
          restore-keys: |
            ${{ runner.os }}-refs/heads/main-gatsby-cache

      - name: Build
        run: npm run build

      - name: Deploy on gh-pages
        if: github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@b8f8d291c97fe0edd9fb4ee73018163593418e8f
        with:
          target_branch: gh-pages
          build_dir: public
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
