name: Test website for regressions

on:
  schedule:
    - cron: "0 12 * * 0,2,5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - uses: php-actions/composer@v6

      - run: composer install

      - name: Test if microformat 2 looks the same on live page.
        # To create new output if anything changes run:

        # composer install && php tests/mf2_regression_test/fetch_mf2.php > \
        #   tests/mf2_regression_test/mf2.json.spec
        shell: bash
        run: |
          diff <(php tests/mf2_regression_test/fetch_mf2.php) \
            tests/mf2_regression_test/mf2.json.spec
