name: Test repo

on:
  push:
    branches-ignore:
      - "gh-pages"
  schedule:
    - cron: "* * * * 1" # every tuesday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Update npm
        run: npm install -g npm@latest

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "npm_cache_dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - name: Restore NPM cache
        uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ env.npm_cache_dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Restore Gatsby cache
        uses: actions/cache@v3
        id: gatsby-cache
        with:
          path: |
            ./.cache
            ./public
          key: ${{ runner.os }}-gatsby-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gatsby-

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
